In [1]:
import requests
from pathlib import Path

def dowanlod_row_file_of_raw_data(year: int, month: int) -> Path:

    url = f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month:02d}.parquet"

    response = requests.get(url)

    if response.status_code == 200:
        path = f"../data/raw/rides_{year}-{month:02d}.parquet"
        open(path, "wb").write(response.content)
        return path
    else:
        raise Exception(f"{url} is not available. Status code: {response.status_code}")

In [2]:
dowanlod_row_file_of_raw_data(year=2026, month=1)

'../data/raw/rides_2026-01.parquet'

In [1]:
import pandas as pd 

rides = pd.read_parquet("../data/raw/rides_2026-01.parquet")

rides.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [2]:
rides = rides[['tpep_pickup_datetime','PULocationID']]

In [3]:
rides.rename(
    columns={
        "tpep_pickup_datetime": "pickup_datetime",
        "PULocationID": "pickup_location_id"
    },
    inplace=True
)
rides.head()

      pickup_datetime  pickup_location_id
0 2026-01-01 00:54:04                 239
1 2026-01-01 00:34:04                 163
2 2026-01-01 00:57:06                  43
3 2026-01-01 00:15:22                 142
4 2026-01-01 00:27:13                  88

In [4]:
rides['pickup_datetime'].describe()

count                       3724889
mean     2026-01-17 01:44:52.106518
min             2025-12-31 23:57:29
25%             2026-01-09 17:51:59
50%             2026-01-16 21:20:56
75%             2026-01-24 07:25:11
max             2026-02-01 00:45:01
Name: pickup_datetime, dtype: object

In [5]:
rides = rides[rides['pickup_datetime'] >= '2026-01-01']
rides = rides[rides.pickup_datetime < '2026-02-01']

rides['pickup_datetime'].describe()

count                       3724882
mean     2026-01-17 01:44:53.996608
min             2026-01-01 00:00:00
25%             2026-01-09 17:52:00
50%             2026-01-16 21:20:57
75%             2026-01-24 07:25:11
max             2026-01-31 23:59:59
Name: pickup_datetime, dtype: object

In [6]:
rides.to_parquet("../data/transformed/validated_rides_2026_01.parquet")