In [11]:
%reload_ext autoreload
%autoreload 2

In [12]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

from src.data import load_row_data

rides = load_row_data(year=2025)
rides

file 2025-01 was already in local storage
file 2025-02 was already in local storage
file 2025-03 was already in local storage
file 2025-04 was already in local storage
file 2025-05 was already in local storage
file 2025-06 was already in local storage
file 2025-07 was already in local storage
file 2025-08 was already in local storage
file 2025-09 was already in local storage
file 2025-10 was already in local storage
file 2025-11 was already in local storage
file 2025-12 was already in local storage

            pickup_datetime  pickup_location_id
0       2025-01-01 00:18:38                 229
1       2025-01-01 00:32:40                 236
2       2025-01-01 00:44:04                 141
3       2025-01-01 00:14:27                 244
4       2025-01-01 00:21:34                 244
...                     ...                 ...
4305001 2025-12-31 23:20:55                 216
4305002 2025-12-31 23:08:47                  22
4305003 2025-12-31 23:29:04                 128
4305004 2025-12-31 23:25:12                 114
4305005 2025-12-31 23:01:11                 236

[48722388 rows x 2 columns]

In [13]:
from src.data import tranfrom_row_data_into_ts_data

ts_data = tranfrom_row_data_into_ts_data(rides)
ts_data

100%|██████████| 262/262 [00:02<00:00, 90.11it/s]

                pickup_hour  rides  pickup_location_id
0       2025-01-01 00:00:00      0                   1
1       2025-01-01 01:00:00      0                   1
2       2025-01-01 02:00:00      0                   1
3       2025-01-01 03:00:00      0                   1
4       2025-01-01 04:00:00      0                   1
...                     ...    ...                 ...
2295115 2025-12-31 19:00:00      4                 265
2295116 2025-12-31 20:00:00      3                 265
2295117 2025-12-31 21:00:00      6                 265
2295118 2025-12-31 22:00:00      3                 265
2295119 2025-12-31 23:00:00      5                 265

[2295120 rows x 3 columns]

In [16]:
from src.data import transform_ts_data_info_feature_and_target

print(transform_ts_data_info_feature_and_target.__module__)

src.data

In [17]:
import importlib
import src.data

importlib.reload(src.data)

from src.data import (
    transform_ts_data_info_feature_and_target,
    get_cutoff_indices,
)

In [18]:
print(get_cutoff_indices)

<function get_cutoff_indices at 0x0000028E99079760>

In [20]:

features, targets = transform_ts_data_info_feature_and_target(
    ts_data,
    input_seq_len=24*28*1, # one month of history
    step_size=24,
)

print(f'{features.shape}')
print(f'{targets.shape}')

100%|██████████| 262/262 [00:29<00:00,  8.92it/s]

(88294, 674)
(88294,)

In [21]:
tabular_data = features
tabular_data['target_rides_next_hour'] = targets

from src.paths import TRASNFORMED_DATA_DIR
tabular_data.to_parquet(TRASNFORMED_DATA_DIR / 'tabular_data.parquet')